plugins {
    id 'java-library'
    id 'org.springframework.boot' apply false
}

dependencies {
    api libs.bundles.commons
    api libs.mapstruct
    api libs.telegrambots.meta

    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.springframework.boot:spring-boot-starter-validation'

    api 'org.jsoup:jsoup:1.23.2'
}

jacocoTestReport {
    classDirectories.setFrom(files(classDirectories.files.collect {
        fileTree(dir: it, exclude: [
                'io/github/yvasyliev/forwarder/telegram/core/configuration/**',
                'io/github/yvasyliev/forwarder/telegram/core/dto/**',
                'io/github/yvasyliev/forwarder/telegram/core/entity/**',
        ])
    }))
}
