name: Demo

on:
  workflow_dispatch:

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      foo: ${{ steps.set.outputs.foo }}
    steps:
      - id: set
        run: |
          echo "foo=bar" >> $GITHUB_ENV
  print-env:
    needs: set-env
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.set-env.outputs.foo }}
