name: Demo

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_ENV"
      - id: step2
        run: echo "test=world" >> "$GITHUB_ENV"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{ needs.job1.outputs.output1 }}
          OUTPUT2: ${{ needs.job1.outputs.output2 }}
        run: echo "$OUTPUT1 $OUTPUT2"

# jobs:
#   set-env:
#     runs-on: ubuntu-latest
#     outputs:
#       foo: ${{ steps.set.outputs.foo }}
#     steps:
#       - id: set
#         run: |
#           echo "foo=bar" >> $GITHUB_ENV
#   print-env:
#     needs: set-env
#     runs-on: ubuntu-latest
#     steps:
#       - env:
#           FOO: ${{ needs.set-env.outputs.foo }}
#         run: |
#           echo $FOO
